// Generated by Skyramp v1.3.24 on 2026-05-19 20:00:21.890523375 +0000 UTC m=+263.720790031
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output collaborate_live_label.spec.ts \
// 		--output-dir /home/runner/work/excalidraw/excalidraw/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/excalidraw/excalidraw/.skyramp/collaborate_live_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(93000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:3000");
    await page.getByTestId("main-menu-trigger").click();
    await expect(page.getByTestId("collab-button")).toHaveText("Collaborate live...");
    expect(errors).toHaveLength(0);
});
